save_folder: "output/bfs_runs"
project_name: "fitness"
version: "v1.0.0"

llm_type:
  manager_crew: "mock"
  planners_crew_creative: "mock"
  planners_crew_balanced: "mock"
  planners_crew_conservative: "mock"
  reviewer_crew: "mock"
  writer_crew: "mock"
