save_folder: "output/bfs_runs"
project_name: "fitness"
version: "v1.0.0"

llm_type:
  manager_crew: "mock"
  designer_crew_creative: "mock"
  designer_crew_balanced: "mock"
  designer_crew_balanced_pydantic: "mock"
  designer_crew_conservative: "mock"
  designer_crew_conservative_json: "mock"
  designer_crew_conservative_pydantic: "mock"
  designer_crew: "mock"
  planners_crew_creative: "mock"
  planners_crew_balanced: "mock"
  planners_crew_conservative: "mock"
  reviewer_crew: "mock"
  writer_crew: "mock"
